export const ADMIN_ROUTE = "/admin"; //Странца админа
export const ADMIN_PANEL_MAIN_ROUTE = "/admin/main"; //Странца админа
export const SELLER_ROUTE = "/seller"; //страница продовца
export const LOGIN_ROUTE = "/login"; //Страница логина
export const REGISTRATION_ROUTE = "/registration"; //Страница регистрации
export const HELPER_ROUTE = "/helper"; //Страница помощи
export const CONTACTS_ROUTE = "/contacts"; //Страница контактов
export const SETTINGS_ROUTE = "/settings"; //Страница настроек
export const SHOP_ROUTE = "/"; //Главная страница
export const FAQ_ROUTE = "/FAQ"; // FAQ
export const CONFIRM_EMAIL_ROUTE = "/confirmEmail";
export const FORGOT_PASSWORD_ROUTE = "/forgot-password"; //Страница восстановления пароля
export const PAGE_NOT_FOUND_ROUTE = "/PageNotFound"; //404 ошибка
export const PRODUCT_ROUTE = "/product"; //Страница товара
export const MAKING_ORDER_ROUTE = "/order"; //Страница оформления заказа
export const PROFILE_ROUTE = "/profile"; //Страница профиля
export const CHANGE_PROFILE_ROUTE = "/profile/change-profile"; // Страницп изменения профиля
export const SELLER_PROFILE_ROUTE = "/profile/seller-profile"; //Профиль продавца
export const BASKET_ROUTE = "/basket"; //Страница корзины
export const WISHLIST_ROUTE = "/wishlist"; //Страница избранных товаров
export const FORGOT_PASSWORD_STEP_TWO_ROUTE = "/forgot-password/enter-code";
export const FORGOT_PASSWORD_STEP_THREE_ROUTE = "/forgot-password/set-password";
export const FEEDBACK_ROUTE = "/profile/feedback"; // Страница с отзывами
export const EDIT_FEEDBACK_ROUTE = "/profile/feedback/edit"; // Страница отправки/редактирования отызва
